services:
  app-dev:
    build:
      context: .
      dockerfile: dockerfile
      ports:
        - "80:3000"
      volumes:
        - .:/app
        - /app/node_modules
    networks:
      - penzi_network